### ISSUE TITLE
Arduino Library Support

### ISSUE THREAD

**Issue by RebbePod** [yparitcher/libzmanim#4]
Is it possible to convert this to an Arduino library?
I'm looking to make a few projects which can greatly benefit from a "issur melacha" Boolean.

**Comment by yparitcher** [comment]
The base hebrew calendar functions (hebrewcalendar.c) only uses the math library for the floor function and the zmanim functions (zmanim.c, NOAAcalculator.c) only uses the C std library for floating point math support. To make this work with Arduino you would need to ensure that the required support is there, either for just the calendar or also for the zmanim. The shiur and date format also require the std library string functions, however they will probably not be needed on an Arduino.
To convert a C date to and from the hebrew date there are 2 functions in hebrewcalendar.c (hdategregorian(hdate date), hdatetime_t(hdate date)) that need to be replaced to handle a Arduino date.

PR's welcome :)

**Comment by RebbePod** [comment]
You have a Boolean in the hebrewcalender library called isassurbemelachah, since it doesn't have access to the zmanim library will it go based off a 12am schedule?

**Comment by emaayan** [comment]
Have you been able to use this library for arduino?

**Comment by RebbePod** [comment]
@emaayan I have been successful in getting it to work with esphome. Please see here
https://github.com/chabad-source/melachaplug

**Comment by emaayan** [comment]
Thanks, will look into it, been meaning to re-create something like this in arduino..

http://www.jewishsoftware.net/judaica/hebrew-watches/the-jewish-desk-clock.html

**Comment by RebbePod** [comment]
Interesting project. I believe you'll find it much easier to recreate using esphome using an ESP chip. (which are supported by Arduino IDE)

**Comment by emaayan** [comment]
> 

thanks i actually have some esp32's laying around, i got from here: https://www.amazon.com/dp/B08246MCL5 
i've started playing around using esp-idf, but that thing's heavy.... i might get back to it, i don't know know much about esphome, esp chip or arduino and why it would be easier , i'm using vscode for everything now.

**Comment by RebbePod** [comment]
Check it out, really simple and powerful.
https://esphome.io/

ESP32s are great (esp chips as in any chip in the esp family)

**Comment by yparitcher** [comment]
As stated above, i do not have plans to port this to the arduino, PR's welcome.

**Comment by emaayan** [comment]
> As stated above, i do not have plans to port this to the arduino, PR's welcome.

yes, i know i'm looking into it now, however i'm not sure code can be made to be portable on both platforms.
there's the build system which here is Makefile while on platform.io it's somethign different, and there's also probable differnet data types that need to be used.

**Comment by RebbePod** [comment]
Thank you @yparitcher #thebest

**Comment by emaayan** [comment]
@yparitcher 
you would be willing to assist  in my efforts to convert, because i'm REALLY trying to make this work.
the main issue i have is build process with hdateformat and stpncpy files ,mainly i'm a java developer 
as you can see from the image below i've managed to get this to work, but only forking your code 

![image](https://user-images.githubusercontent.com/13434544/217459061-22a3fd99-7e56-45b1-ba56-38ad2d267417.png)

the main problem is that i'm callling c code from cpp, and i keep getting undefined reference to stpncpy 
the only way i've managed to work around this is by renaming stpncpy and hdataformat to cpp and using extern , but i'd rather avoid that. other than that i would need to do some small code changes in hebrewcaldner but that shouldn't be an issue, the main problem is the build process.

essentially all one has to do to make this into a arduino library platfrom.io can consume is create library.json file that relies on src and include folder by default, so we are allready half way there.. 
```
{
  "$schema": "https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/schema/library.json",
  "name": "Libzmanim",
  "version": "1.0-1",
  "description": "a C library for zmanim and hebrew dates",
  "repository": {
    "type": "git",
    "url": "git://github.com/yparitcher/libzmanim"
  },
  "build": {   
    "srcFilter": " -<*> -<src/hebdateformat.c>  +<windows/stpncpy.c> "
  },
  "authors": [
    {
      "name": "Yparitcher",
      "email": "support@paritcher.com",
      "url": "https://paritcher.com/"
    }
  ],
  "license": "MIT",
  "frameworks": "*",
  "platforms": "*"
}
```
